############################################################################
# FILE   : makefile
# AUTHOR : Peter C. Chapin <peter@pchapin.org>
#
# This is the makefile for the SpicaC project.
############################################################################

!include master.mif

.c:     ..\..
.c.obj: .AUTODEPEND
    wcc386 $(c_options) /bt=os2 $[*.c
