############################################################################
# FILE   : makefile
# AUTHOR : Peter C. Chapin <peter@pchapin.org>
#
# This is the makefile for the SpicaC project.
############################################################################

!include master.mif

.c:     ..\..
.c.obj: .AUTODEPEND
    wcc $(c_options) /ml /bt=dos $[*.c
